language: python

install:
  - pip3 install -r requirements.txt

script:
  - mkdocs build --clean --strict --verbose
  - touch ./site/.nojekyll
  - cp CNAME ./site
  - date -Iseconds >> ./site/build.info.txt

deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  deployment_file: true
  verbose: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
