# Main settings for asynx.dev

title: ayazar's personal space
name: Alper Yazar
description: "PhD candidate and electronics engineer"
baseurl: ""
url: ""
author: ayazar

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: contrast
source: src
timezone: Europe/Istanbul
search: true

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-archives

include:
  - _pages

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      show_date: true
      permalink: /log/:year/:month/:slug:output_ext
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      toc: false
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
      toc: false

category_archive:
  type: jekyll-archives
  path: /log/categories/
tag_archive:
  type: jekyll-archives
  path: /log/tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /log/categories/:name/
    tag: /log/tags/:name/

collections:
  projects:
    output: true
    permalink: /:collection/:path:output_ext
  publications:
    output: true
    permalink: /:collection/:path:output_ext

footer:
  links:
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-0904-9623"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Alper-Yazar"
    - label: "Publons"
      # publons icon is not available yet, this is an ugly replacement.
      icon: "far fa-fw fa-sticky-note"
      url: "https://publons.com/researcher/E-7451-2019/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://www.linkedin.com/in/alperyazar"
    - label: "Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com.tr/citations?hl=tr&user=yLCD7acAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alperyazar"
    - label: "Hackaday"
      icon: "fas fa-fw fa-skull-crossbones"
      url: "https://hackaday.io/ayazar"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/alper_yazar"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/user/ayazar/"
    - label: "Stack Exchange"
      icon: "fab fa-fw fa-stack-exchange"
      url: "http://stackexchange.com/users/1966184/alper-y"
    - label: "YouTube Channel"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/user/alperyazar"
    - label: "Facebook Page"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/alperyazarcom"
