copyright: "Copyright &copy; 2011-2021 Alper Yazar<br/>License: <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC-BY-SA-4.0</a>"
site_author: Alper Yazar
# site_description: Personal Site !! Not used to use custom meta description code.
site_name: Alper Yazar
site_url: http://localhost:8000/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - toc:
      permalink: false


plugins:
  - bibtex:
      bib_file: "ref/refs.bib"
      cite_style: "pandoc"
  - git-revision-date

theme:
  name: null
  logo: img/alper_yazar.png
  favicon: img/favicon.ico
  custom_dir: ayazar_theme

nav:
  - About: index.md
  - Contact - İletişim: contact.md
  - Blog: blog/index.md
  - Notebook:
    - Knowledge Base: nb/kb/index.md
    - Notes: nb/n/index.md
    - Reviews - İncelemeler: nb/r/index.md
  - Misc.: misc/index.md
