copyright: "License: <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC-BY-SA-4.0</a>"
repo_url: https://github.com/alperyazar/www/
site_author: Alper Yazar
site_description: Personal Site
site_name: Alper Yazar
site_url: http://www.ayazar.com/

markdown_extensions:
  - footnotes
  - admonition

plugins:
  - search

theme:
  name: cinder
  custom_dir: cinder-theme-ext
  highlightjs: true
  hljs_languages:
    - matlab
    - latex

nav:
  - About: index.md
  - Contact: contact.md
  - Blog: blog/index.md
  - Notebook:
    - Dictionary: nb/d/index.md
    - Knowledge Base: nb/kb/index.md
    - Notes: nb/n/index.md
    - Review: nb/r/index.md
    - Lists: nb/l/index.md
  - Misc.: misc/index.md
