copyright: "CC-BY-SA-4.0"
google_analytics: ['UA-155131137-1', 'ayazar.com']
repo_url: https://github.com/alperyazar/www/
site_author: Alper Yazar
site_description: Personal Site
site_name: Alper Yazar
#site_url: https://www.ayazar.com

markdown_extensions:
  - footnotes

plugins:
  - search
  - git-revision-date

theme:
  name: cinder
  custom_dir: cinder-theme-ext
